baseURL = 'https://nusbru.github.io/blog'
copyright = "{year}"
languageCode = 'pt-BR'
defaultContentLanguage = 'en'
theme = 'clean-theme'
title = 'Bruno'
enableRobotsTXT = true
summaryLength = 15
paginate = 5
staticDir = ['static']
canonifyURLs = true 


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
